<?php

namespace AppBundle\Repository;

/**
 * IN_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IN_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
