AppBundle\Entity\IN_User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\IN_UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bornYear:
            type: datetime
            column: born_year
        fullName:
            type: string
            length: '40'
            column: full_name
    lifecycleCallbacks: {  }
