AppBundle\Entity\InLocation:
    type: entity
    table: in_location
    uniqueConstraints:
        UNIQ_1967F5972D5B0234:
            columns:
                - city
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        city:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
    manyToMany:
        user:
            targetEntity: InUser
            cascade: {  }
            fetch: LAZY
            mappedBy: location
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
