AppBundle\Entity\InUser:
    type: entity
    table: in_user
    uniqueConstraints:
        UNIQ_A728E92D92FC23A8:
            columns:
                - username_canonical
        UNIQ_A728E92DA0D96FBF:
            columns:
                - email_canonical
        UNIQ_A728E92DC05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        confirmationToken:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
        bornYear:
            type: date
            nullable: false
            column: born_year
        facebook_id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: facebook_id
        facebook_access_token:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: facebook_access_token
        google_id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: google_id
        google_access_token:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: google_access_token
        fullName:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            column: full_name
    manyToMany:
        location:
            targetEntity: InLocation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: in_user_location
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: location_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
