AppBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        UNIQ_1483A5E992FC23A8:
            columns:
                - username_canonical
        UNIQ_1483A5E9A0D96FBF:
            columns:
                - email_canonical
        UNIQ_1483A5E9C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        birthDate:
            type: datetime
            nullable: true
            column: birth_date
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        facebook_id:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        facebook_access_token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        google_id:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        google_access_token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fullName:
            type: string
            nullable: true
            length: 21
            options:
                fixed: false
            column: full_name
    manyToMany:
        region:
            targetEntity: Regions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_regions
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: region_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
